version: '3.8'
services:
  jupyter-lab:
    build: ./SG3_tune
    ports:
      - "8888:8888"
    volumes:
      - ./SG3_tune:/SG3_tune
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]